import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Form = (props) => (
  <form onSubmit={props.handleSubmit}>
    <label>
      ウィッシュ：
      <input type='text' value={props.value} onChange={props.handleChange} />
    </label>
    <input type='submit' value='追加' disabled={props.value ? false : true} />
  </form>
);

const List = (props) => (
  <ul>
    {props.items.map((item) => (
      <li>{item}</li>
    ))}
  </ul>
);

const Home = () => {
  const [value, setValue] = useState('');
  const [items, setItems] = useState([]);

  const handleChange = (e) => {
    setValue(e.target.value);
  };

  const handleSubmit = (e) => {
    items.push(value);
    setItems(items);
    setValue('');
    e.preventDefault();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>ウィッシュリスト</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ウィッシュリスト</h1>

        <p className={styles.description}>
          <Form
            handleSubmit={handleSubmit}
            value={value}
            handleChange={handleChange}
          />
        </p>

        <List items={items} />
      </main>
    </div>
  );
};

export default Home;
